version: "3.7"
services:
    app:
        build: . # Dockerfile
        ports: 
            - 8080:8080
        links: 
            - mongodb
    mongodb:
        image: mongo:4.4.3
        restart: always
        container_name: "mongodb"
        ports: 
            - 27017:27017